# Generated by Django 3.0.5 on 2020-06-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_text', models.CharField(max_length=200)),
                ('key_ip', models.CharField(max_length=20)),
            ],
        ),
    ]
